### PR TITLE
fix: sourcesContent not being escaped

### LINKED ISSUE #8: bug: sourcesContent isn't escaped
```js
export const IS_PROD = process.env.NODE_ENV === 'production'
```
Is transformed to
```js
sourcesContent:["export const IS_PROD = "development" === 'production'\n"]
```
Resulting in `Uncaught SyntaxError: Unexpected identifier` at runtime

### PR DESCRIPTION
**Pull request by joshwooding**
Fixes #8

### CODE REVIEW

**Comment by iFaxity** [comment]
Fantastic, looks good.

I don't really like using deletes as it goes against the GC.
But if would be a problem later then we can just patch it to use object spread instead.

I'll merge it when i've gone through my tests.

Thanks!

**Comment by iFaxity** [comment]
Did some minor refactoring after testing to fit the existing code.

**Comment by iFaxity** [comment]
Thanks for your contribution @joshwooding!

**Comment by joshwooding** [comment]
Thanks for the quick release @iFaxity :)

**Pull request merged**
