### PR TITLE
A few different fixes/features

### PR DESCRIPTION
**Pull request by AlexandreBonaventure**
Hello, this plugin was really helpful for us, and trying it we had to tweak it to make it work. 
Summary:
**Fixes**
1) It should skip virtual modules otherwise it runs into the same kind of issues highlighted here: https://github.com/rollup/rollup-plugin-commonjs/issues/397

2) It enforces sourcemapping with `config.build.sourcemap = true` (defaulting to false now in Vite). If disabled, `this.getCombinedSourceMap` is empty 

**Feature**
Add a `cwd` option that is getting forwarded to Istanbul matcher, in case your not calling vite command in the same folder

Thanks for the great work!

### CODE REVIEW

**Comment by iFaxity** [comment]
Hey @AlexandreBonaventure, could you please enable the "Allow edits from maintainers" in the PR. 

I have some documentation i want to make and also a commit in the Angular format in order for the CD to publish the package correctly.

**Comment by AlexandreBonaventure** [comment]
@iFaxity Hello, I don't think I have the right permissions to do that ?? (or maybe I'm missing something) I can't see any checkbox here...
Screen Shot 2021-11-26 at 3 37 31 PM

**Comment by AlexandreBonaventure** [comment]
Maybe that's because the PR was made in my organization... I can rebase with your changes if that's easier

**Comment by iFaxity** [comment]
Could also be because the repo has workflows in both the fork as there are in the main repo. I'll put up a branch with the changes and you can revise them into your PR branch.

**Comment by AlexandreBonaventure** [comment]
sounds good

**Comment by iFaxity** [comment]
There should now be a branch named feature-pr-10 on the remote.

**Comment by AlexandreBonaventure** [comment]
@iFaxity I merged it, back to you !

**Comment by iFaxity** [comment]
Great stuff @AlexandreBonaventure , thanks for your contribution 🙂👍.

**Pull request merged**
